config/urls.py
from django.contrib import admin
from django.urls import path, include

from teams.views import PickListView, PlayerAutoCompleteView, NextPickView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', PickListView.as_view(), name='pick_list'),
    path('players-auto-complete/', PlayerAutoCompleteView.as_view(), name='player_auto_complete'),
    path('next-pick/', NextPickView.as_view(), name='next_pick'),
]

teams/models.py
import uuid
from datetime import datetime

from django.db import models

from users.models import User

def current_year():
    return datetime.now().year


class Team(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    image = models.URLField(max_length=300, null=True, blank=True)
    users = models.ManyToManyField(User)

    def __str__(self):
        return f"{self.city} {self.name}"

    class Meta:
        ordering = ['city', 'name']


class Player(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250)
    position = models.CharField(max_length=100, blank=True)
    overall = models.IntegerField(null=True, blank=True)
    number = models.CharField(max_length=250, blank=True)
    year = models.CharField(max_length=4, default=current_year)

    def __str__(self):
        if self.number and self.position and self.name and self.overall:
            return f"#{self.number} - {self.position} - {self.name} ({self.overall}OV)"
        if not self.number and self.position and self.name and self.overall:
            return f"{self.position} - {self.name} ({self.overall}OV)"
        if self.number and not self.position and self.name and self.overall:
            return f"#{self.number} - {self.name} ({self.overall}OV)"
        if self.number and self.position and self.name and not self.overall:
            return f"#{self.number} - {self.position} - {self.name}"
        if not self.number and not self.position and self.name and self.overall:
            return f"{self.name} ({self.overall}OV)"
        if self.number and not self.position and self.name and not self.overall:
            return f"#{self.number} - {self.name}"
        return f"{self.name}"

    class Meta:
        ordering = ['name']


class Pick(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = models.SmallIntegerField()
    round = models.SmallIntegerField()
    original_team = models.ForeignKey(Team, on_delete=models.PROTECT, related_name='original_team')
    current_team = models.ForeignKey(Team, on_delete=models.PROTECT, related_name='current_team')
    player = models.OneToOneField(Player, null=True, blank=True, on_delete=models.PROTECT)
    picked = models.BooleanField(default=False)
    year = models.CharField(max_length=4, default=current_year)

    class Meta:
        unique_together = [('number', 'round', 'year'), ('round', 'original_team', 'year')]
        ordering = ['number']

    def __str__(self):
        return f"{self.round}/{self.number} {self.current_team}"

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

teams/forms.py
from dal import autocomplete
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple

from teams.models import Player
from users.models import User


class PlayerForm(forms.ModelForm):
    player_name = forms.ModelChoiceField(
        queryset=Player.objects.all(),
        widget=autocomplete.ModelSelect2(url='player_auto_complete')
    )

    class Meta:
        model = Player
        fields = ('player_name',)


class TeamForm(forms.ModelForm):
    users = forms.ModelMultipleChoiceField(
        widget=FilteredSelectMultiple(verbose_name='Users', is_stacked=False),
        queryset=User.objects.all(),
        required=False,
    )


class PickForm(forms.ModelForm):
    users = forms.ModelMultipleChoiceField(
        widget=FilteredSelectMultiple(verbose_name='Users', is_stacked=False),
        queryset=User.objects.all(),
        required=False,
    )

teams/views.py
from datetime import datetime

from dal import autocomplete
from django.db.models import Q
from django.http import JsonResponse
from django.views import View
from django.views.generic import ListView

from teams.forms import PlayerForm
from teams.models import Pick, Player


class PickListView(ListView):
    model = Pick
    ordering = ('round', 'number',)

    def get_queryset(self):
        current_year = datetime.now().year
        return self.model.objects.filter(year=current_year)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PlayerForm()
        return context


class PlayerAutoCompleteView(autocomplete.Select2QuerySetView):

    def get_queryset(self):
        current_year = datetime.now().year
        qs = Player.objects.filter(pick__isnull=True, year=current_year)

        if self.q:
            qs = qs.filter(Q(name__icontains=self.q))

        return qs


class NextPickView(View):

    @staticmethod
    def get(request):
        current_year = datetime.now().year
        pick = Pick.objects.filter(picked=False, year=current_year).order_by('number').first()
        data = dict()
        if pick:
            data['pick_number'] = pick.number
        return JsonResponse(data)

templates/base.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Django Drafter</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'styles/main.css' %}">

  {% block styles %}{% endblock %}
</head>
<body>

<nav class="navbar sticky-top navbar-dark bg-dark">
  <span class="navbar-brand mb-0 h1">Repêchage LNHVQ 2020</span>
  {% if user.is_authenticated %}
    <a class="btn btn-outline-light" href="{% url 'logout' %}"
       data-toggle="tooltip" data-placement="left" title="Déconnexion">
      <i class="fas fa-fw fa-power-off"></i>
      <span class="d-none d-sm-inline-block">Déconnexion</span>
    </a>
  {% else %}
    <a class="btn btn-success" href="{% url 'login' %}"
       data-toggle="tooltip" data-placement="left" title="Connexion">
      <i class="fas fa-fw fa-power-off"></i>
      <span class="d-none d-sm-inline-block">Connexion</span>
    </a>
  {% endif %}
</nav>

<div class="container">
  {% block content %}{% endblock %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/a9c187fa5c.js" crossorigin="anonymous"></script>

{% block scripts %}{% endblock %}

</body>
</html>

templates/teams/pick_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

  <div class="modal" id="modal_select_player" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Sélectionner un joueur</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{ form.player_name }}
          <div class="alert alert-danger" role="alert" id="missing-player">
            Veuillez choisir un joueur avant de cliquer sur Sélectionner.
          </div>
        </div>
        <div class="modal-footer">
          <input type="hidden" id="pick-number">
          <button type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="bottom"
                  title="Si vous ne voulez pas sélectionner de joueur." onclick="skipPlayer()">
            <i class="fas fa-fw fa-ban"></i>Passe
          </button>
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
            <i class="fas fa-fw fa-times"></i>Annuler
          </button>
          <button type="button" class="btn btn-success" onclick="choosePlayer()">
            <i class="fas fa-fw fa-check"></i>Sélectionner
          </button>
        </div>
      </div>
    </div>
  </div>

  {% regroup pick_list by round as round_pick_list %}

  {% for pick in round_pick_list %}
    <section class="affix">
      <h3>Ronde {{ pick.grouper }}</h3>
      <table class="table table-striped table-hover">
        <thead class="thead-dark">
        <tr>
          <th scope="col" style="width: 10%">#</th>
          <th scope="col" style="width: 25%">Équipe originale</th>
          <th scope="col" style="width: 25%">Appartient à</th>
          <th scope="col" style="width: 40%">Joueur</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        </tr>
        {% for item in pick.list %}
          <tr>
            <th scope="row">{{ item.number }}</th>
            <td>
              <div data-toggle="tooltip" data-placement="right" title="{{ item.original_team }}"
                   class="img{% if item.current_team != item.original_team %} smaller{% endif %}"
                   {% if item.original_team.image %}style="background-image:url('{{ item.original_team.image }}')"{% endif %}></div>
            </td>
            <td>
              {% if item.current_team != item.original_team %}
                <div data-toggle="tooltip" data-placement="right" title="{{ item.current_team }}" class="img"
                     style="background-image:url('{{ item.current_team.image }}')"></div>
              {% endif %}
            </td>
            <td id="pick-{{ item.number }}">
              {% if item.picked and user in item.current_team.users.all %}
                <b>{{ item.player|default:"Aucun" }}</b> <span class="badge badge-pill badge-success">Sélectionné</span>
              {% elif item.picked %}
                {{ item.player|default:"Aucun" }}
              {% elif user in item.current_team.users.all or user.is_staff %}
                <button type="button" disabled="disabled"
                        class="select-player-btn btn btn-outline-dark btn-sm btn-block"
                        data-toggle="modal" data-number="{{ item.number }}"
                        data-target="#modal_select_player"
                        data-toggle="tooltip" data-placement="top" title="Sélectionner un joueur">
                  <i class="fas fa-user-check"></i>
                  <span class="d-none d-sm-inline-block">Sélectionner un joueur</span>
                </button>
              {% endif %}
            </td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
    </section>
  {% endfor %}

{% endblock %}

{% block scripts %}
  <script>
    var ws_scheme = window.location.protocol === "https:" ? "wss" : "ws";
    let socket = new WebSocket(ws_scheme + '://' + window.location.host + '/ws/pick/');

    socket.onmessage = (e) => {
      let data = JSON.parse(e.data);
      let playerName = data['player_name'];
      let pickNumber = data['pick_number'];
      $("#pick-" + pickNumber).html(playerName);

      enable_next_pick();
    };

    socket.onclose = (e) => console.error('Chat socket closed unexpectedly', e);
    socket.onerror = (e) => console.error(e);
    socket.onopen = (e) => console.debug('Socket open', e);

    function enable_next_pick() {
      $.ajax({
        url: '/next-pick/',
        type: 'get',
        dataType: 'json',
        success: function (data) {
          $('#modal_select_player').modal('hide');
          if ('pick_number' in data) {
            let playerElement = $('#pick-' + data['pick_number'] + ' .select-player-btn[disabled]');
            if (playerElement.length)
              playerElement.first().attr('disabled', false);
            $('html, body').animate({
              scrollTop: $('.select-player-btn:not([disabled])').offset().top - 350
            }, 1000);
          }
        },
        complete: function () {
          $("#id_player_name").val('');
          $('#select2-id_player_name-container').html('');
        }
      });
    }

    function choosePlayer() {
      let pickNumber = $('#pick-number').val();
      let playerId = $('#id_player_name').val();
      let playerName = $('#select2-id_player_name-container').html();

      if (playerId) {
        socket.send(JSON.stringify({
          'player_id': playerId,
          'player_name': playerName,
          'pick_number': pickNumber,
        }));
        $('#missing-player').hide();
      } else {
        $('#missing-player').show();
      }
    }

    function skipPlayer() {
      let pickNumber = $('#pick-number').val();
      socket.send(JSON.stringify({
        'player_id': null,
        'player_name': 'Aucun',
        'pick_number': pickNumber,
      }));
    }

    function fixTitle() {
      $('section.affix').each(function () {
        let $this = $(this);
        let offset = $this.offset().top;
        let scrollTop = $(window).scrollTop() + 100;

        if (scrollTop > offset) {
          $this.addClass('fixed');
        } else {
          $this.removeClass('fixed');
        }
      });
    }

    $(document).ready(function () {
      // Do this before you initialize any of your modals
      $.fn.modal.Constructor.prototype._enforceFocus = function () {
      };

      $('#modal_select_player').on('show.bs.modal', function (event) {
        let button = $(event.relatedTarget);
        let pickNumber = button.data('number');
        $('#pick-number').val(pickNumber);
      });

      $('[data-toggle="tooltip"]').tooltip();

      $('#missing-player').hide();

      $(window).scroll(fixTitle);

      enable_next_pick();
    });
  </script>
  {{ form.media }}
{% endblock %}